basic:
    name: 'Bud Auer'
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'https://sawayn.com/'
        - 'https://www.cassin.com/sunt-quia-quos-similique-architecto'
    monitoring:
        days: {  }
        type: ''
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: ''
    retina_images: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: multiple-sites
